formatter: "markdown table" # this is required

version: ""

header-from: docs/header.md
footer-from: docs/footer.md

recursive:
  enabled: false

sections:
  show: 
    - header
    - providers
    - inputs
    - outputs
    - footer

content: |-
  {{ .Header }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}  

  {{ .Footer }}  

output:
  file: README.md
  mode: inject
  template: |- 
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}

    <!-- END_TF_DOCS -->

output-values:
  enabled: false

sort:
  enabled: false

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: false
  read-comments: false
  required: true
  sensitive: true
  type: true
